/**
 * generated by Xtext 2.10.0
 */
package org.example.domainmodel.tests;

import com.google.inject.Inject;
import org.eclipse.xtend2.lib.StringConcatenation;
import org.eclipse.xtext.junit4.InjectWith;
import org.eclipse.xtext.junit4.XtextRunner;
import org.eclipse.xtext.junit4.util.ParseHelper;
import org.eclipse.xtext.junit4.validation.ValidationTestHelper;
import org.eclipse.xtext.xbase.lib.Exceptions;
import org.eclipse.xtext.xbase.lib.Extension;
import org.example.domainmodel.domainmodel.Domainmodel;
import org.example.domainmodel.tests.DomainmodelInjectorProvider;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;

@RunWith(XtextRunner.class)
@InjectWith(DomainmodelInjectorProvider.class)
@SuppressWarnings("all")
public class DomainmodelParsingTest {
  @Inject
  @Extension
  private ParseHelper<Domainmodel> _parseHelper;
  
  @Inject
  @Extension
  private ValidationTestHelper _validationTestHelper;
  
  @Test
  public void empty() {
    try {
      StringConcatenation _builder = new StringConcatenation();
      _builder.append("entity foo {}");
      _builder.newLine();
      final Domainmodel result = this._parseHelper.parse(_builder);
      Assert.assertNotNull(result);
      this._validationTestHelper.assertNoErrors(result);
    } catch (Throwable _e) {
      throw Exceptions.sneakyThrow(_e);
    }
  }
  
  @Test
  public void example() {
    try {
      StringConcatenation _builder = new StringConcatenation();
      _builder.append("import java.util.List");
      _builder.newLine();
      _builder.append(" ");
      _builder.newLine();
      _builder.append("package my.model {");
      _builder.newLine();
      _builder.append(" ");
      _builder.newLine();
      _builder.append("    ");
      _builder.append("entity Person {");
      _builder.newLine();
      _builder.append("        ");
      _builder.append("name: String");
      _builder.newLine();
      _builder.append("        ");
      _builder.append("firstName: String");
      _builder.newLine();
      _builder.append("        ");
      _builder.append("friends: List<Person>");
      _builder.newLine();
      _builder.append("        ");
      _builder.append("address : Address");
      _builder.newLine();
      _builder.append("        ");
      _builder.append("op getFullName() : String {");
      _builder.newLine();
      _builder.append("            ");
      _builder.append("return firstName + \" \" + name;");
      _builder.newLine();
      _builder.append("        ");
      _builder.append("}");
      _builder.newLine();
      _builder.append("        ");
      _builder.newLine();
      _builder.append("        ");
      _builder.append("op getFriendsSortedByFullName() : List<Person> {");
      _builder.newLine();
      _builder.append("            ");
      _builder.append("return friends.sortBy[ f | f.fullName ]");
      _builder.newLine();
      _builder.append("        ");
      _builder.append("}");
      _builder.newLine();
      _builder.append("    ");
      _builder.append("}");
      _builder.newLine();
      _builder.append("    ");
      _builder.newLine();
      _builder.append("    ");
      _builder.append("entity Address {");
      _builder.newLine();
      _builder.append("        ");
      _builder.append("street: String");
      _builder.newLine();
      _builder.append("        ");
      _builder.append("zip: String");
      _builder.newLine();
      _builder.append("        ");
      _builder.append("city: String");
      _builder.newLine();
      _builder.append("    ");
      _builder.append("}");
      _builder.newLine();
      _builder.append("}");
      _builder.newLine();
      final Domainmodel result = this._parseHelper.parse(_builder);
      this._validationTestHelper.assertNoErrors(result);
    } catch (Throwable _e) {
      throw Exceptions.sneakyThrow(_e);
    }
  }
  
  @Test
  public void loop() {
    try {
      StringConcatenation _builder = new StringConcatenation();
      _builder.append("import java.util.List");
      _builder.newLine();
      _builder.append(" ");
      _builder.newLine();
      _builder.append("package my.model {");
      _builder.newLine();
      _builder.append(" ");
      _builder.newLine();
      _builder.append("    ");
      _builder.append("entity Person {");
      _builder.newLine();
      _builder.append("        ");
      _builder.append("name: String");
      _builder.newLine();
      _builder.append("        ");
      _builder.append("friends: List<Person>");
      _builder.newLine();
      _builder.append("        ");
      _builder.append("op findFriend(Person name) : Person {");
      _builder.newLine();
      _builder.append("            ");
      _builder.append("for (var int i = 0; i < friends.size; i++) {");
      _builder.newLine();
      _builder.append("                ");
      _builder.append("val friend = friends.get(i)");
      _builder.newLine();
      _builder.append("                ");
      _builder.append("if (friend.name == name) {");
      _builder.newLine();
      _builder.append("                    ");
      _builder.append("return friend");
      _builder.newLine();
      _builder.append("                ");
      _builder.append("}");
      _builder.newLine();
      _builder.append("            ");
      _builder.append("}");
      _builder.newLine();
      _builder.append("            ");
      _builder.append("return null");
      _builder.newLine();
      _builder.append("        ");
      _builder.append("}");
      _builder.newLine();
      _builder.append("    ");
      _builder.append("}");
      _builder.newLine();
      _builder.append("}");
      _builder.newLine();
      final Domainmodel result = this._parseHelper.parse(_builder);
      this._validationTestHelper.assertNoErrors(result);
    } catch (Throwable _e) {
      throw Exceptions.sneakyThrow(_e);
    }
  }
}
